;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  Subreg       = (/ "North Pacific",  "CONUS",  "Tropics"/)
  Subrgs       = (/ "NP",  "CONUS",  "Trop"/)
  minlat       = (/  10.0,   25.0,  -10.0/)
  maxlat       = (/  65.0,   50.0,   10.0/)
  minlon       = (/ 110.0,  150.0,   60.0/)
  maxlon       = (/ 260.0,  300.0,  270.0/)
  nsubreg      = dimsizes(Subreg)
