  varList    = (/"PSL","PRECT","PRECST","SST","TS","TREFHT","TMQ", \
                 "CLDLOW", "CLDTOT","U10","TGCLDLWP","TGCLDIWP", \
                 "TAUX","TAUY", "LWCF","SWCF", "NETCF", \
                 "LWCF_SRF", "SWCF_SRF","NETCF_SRF", \
                 "LHFLX", "SHFLX", "FLNS","FSNS", \
                 "FLNSC","FSNSC", "RESTOA", \
                 "NET_FLUX_SRF","NET_RAD_FLUX_SRF"/)
  untList    = (/"Pa", "mm day~S~-1~N~", "mm day~S~-1~N~", "K","K", "K", "g m~S~-2~N~", \
                 "percent","m s~S~-1~N~", "g m~S~-2~N~","g m~S~-2~N~", \
                 "N m~S~-2~N~", "N m~S~-2~N~", "unitless", "unitless", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~"/)
