  varList  = (/"PSL","PRECT","PRECST","TS","TREFHT","TMQ", \
               "CLDLOW","CLDTOT","U10","V10","S10",\
               "TGCLDLWP","TGCLDIWP","TAUX","TAUY","LHFLX","SHFLX", \
               "FSUS","FSDS","FSUSC","FSDSC", \
               "FLUS","FLUSC","FLDS", "FLDSC", \
               "FSNS","FSNSC","FLNS","FLNSC", \
               "ALBEDO_SRF","NET_RAD_FLUX_SRF", \
               "NET_FLUX_SRF", "CRE_SRF", "Qn_SRF", "LWCF_SRF", \
               "SWCF_SRF","NETCF_SRF", "LWCF","SWCF","NETCF","RESTOA"/)
  facList  = (/1.0, 8.64e7, 8.64e7, \
               1, 1, 1e3,    \
               100, 100,     \
               1, 1, 1,      \
               1e3, 1e3,     \
               -1, -1, 1, 1, \
               1, 1, 1, 1,   \
               1, 1, 1, 1,   \
               1, 1, 1, 1,   \
               1, 1, 1, 1,   \
               1, 1, 1, 1,   \
               1, 1, 1, 1, 1, 1 /)
  untList  = (/"Pa", "mm day~S~-1", "mm day~S~-1", \
               "K", "K", "g m~S~-2~N~", \
               "percent","percent", \
               "m s~S~-1~N~","m s~S~-1~N~","m s~S~-1~N~", \
               "g m~S~-2~N~","g m~S~-2~N~", \
               "N m~S~-2~N~", "N m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
               "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~" /)

