  varList    = (/"FSUS","FSDS","FSUSC","FSDSC", \
                 "FLUS","FLUSC","FLDS", "FLDSC", \
                 "FSNS","FSNSC","FLNS","FLNSC", \
                 "ALBEDO_SRF","NET_RAD_FLUX_SRF", \
                 "NET_FLUX_SRF", "LWCF_SRF", \
                 "SWCF_SRF","NETCF_SRF", \
                 "CRE_SRF", "Qn_SRF",\
                 "LWCF","SWCF","NETCF","RESTOA"/)
  facList    = (/1, 1, 1, 1, \
                 1, 1, 1, 1, \
                 1, 1, 1, 1, \
                 1, 1, 1, 1, \
                 1, 1, 1, 1, \
                 1, 1, 1, 1 /)
  untList    = (/"W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~" /)
