
  VarList  = (/"CLDLOW","CLDHGH","CLDMED","CLDTOT",
               "FLDS","FLNS","FLNSC","FLNT","FLNTC",
               "FLUT","FLUTC","FSDS","FSDSC","FSNS",
               "FSNSC","FSNT","FSNTC","FSNTOA","FSNTOAC",
               "FSUTOA","FSUTOAC","LHFLX","SHFLX","LWCF",
               "SWCF","PRECC","PRECL","TAUX","TAUY",
               "TGCLDCWP","TGCLDIWP","TGCLDLWP","TMQ",
               "TROP_P","TROP_T","TH7001000","PBLH","TREFHT",
               "QREFHT","PS","TS","U10","OMEGA500"/)
