  varList    = (/"PSL","PRECT","PRECST","TS","TREFHT","TMQ", \
                 "CLDTOT","U10","TGCLDLWP","TGCLDIWP", \
                 "TAUX","TAUY", "ALBEDO", "ALBEDO_SRF", \
                 "LWCF","SWCF", "NETCF", \
                 "LWCF_SRF", "SWCF_SRF","NETCF_SRF", \
                 "LHFLX", "SHFLX", \  ;"RESSURF", \
                 "FLNS","FSNS", \ ;"NetRad_SRF",\
                 "FLNSC","FSNSC" \ ;"NetRad_SRF_clr" /)
                  /)
  untList    = (/"Pa", "mm day~S~-1", "mm day~S~-1", "K", "K", "g m~S~-2~N~", \
                 "percent","m s~S~-1~N~", "g m~S~-2~N~","g m~S~-2~N~", \
                 "N m~S~-2~N~", "N m~S~-2~N~", "unitless", "unitless", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~", \
                 "W m~S~-2~N~", "W m~S~-2~N~", "W m~S~-2~N~" /)
