
 ;;;;;;variables to be plotted;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  nvar2     = 5
  VarList2  = new(nvar2, "string")
  VstList2  = new(nvar2, "string")
  VnmList2  = new(nvar2, "string")
  UnitList2 = new(nvar2, "string")

  ivar2 = 0 
  VarList2(ivar2) = "AODVIS"
  VstList2(ivar2) = "AODVIS"
  VnmList2(ivar2) = "AODVIS"
  UnitList2(ivar2)= "unitless"

  ivar2 = ivar2+1
  VarList2(ivar2) = "AODALL"
  VstList2(ivar2) = "AODALL"
  VnmList2(ivar2) = "AODALL"
  UnitList2(ivar2)= "unitless"

  ivar2 = ivar2+1
  VarList2(ivar2) = "BURDEN1"
  VstList2(ivar2) = "BURDEN1"
  VnmList2(ivar2) = "BURDEN1"
  UnitList2(ivar2)= "10~S~-5~N~ kg m~S~-2~N~"

  ivar2 = ivar2+1
  VarList2(ivar2) = "BURDEN2"
  VstList2(ivar2) = "BURDEN2"
  VnmList2(ivar2) = "BURDEN2"
  UnitList2(ivar2)= "10~S~-7~N~ kg m~S~-2~N~"

  ivar2 = ivar2+1
  VarList2(ivar2) = "BURDEN3"
  VstList2(ivar2) = "BURDEN3"
  VnmList2(ivar2) = "BURDEN3"
  UnitList2(ivar2)= "10~S~-5~N~ kg m~S~-2~N~"

